title: Adam Leary
remote_theme: "jekyll/minima@1e8a445"
mermaid: true
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
header_pages:
  - index.md
  - about.md
  - contact.md
  - projects.md
  - leadership.md
  - architecture.md
  - blog.md
